### ISSUE TITLE
Define and discuss the carbonaut roadmap

### ISSUE THREAD

**Issue by leonardpahlke** [carbonaut-cloud/community#11]
A number of topics have been created to drive the Carbonaut project forward. On the project board "Carbonaut Roadmap" these topics are listed. Some topics are certainly still missing and need to be added. In order to properly define *desired dates*, priorities and milestones of the issues, a discussion is necessary. 

From the top of my head I would create milestones in this structure:
- [x] Tasks before setting carbonaut online
- [x] Tasks before first caronaut release
- [ ] To create the first carbonaut release
- [ ] Tasks beyond the first release
